name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.5.1
      -
        name: Set up Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.18
      -
        name: Run build
        run: go build . 
      -
        name: Run vet & lint
        run: go vet .
