name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      -
        name: Run build
        run: go build . 
      -
        name: Run vet & lint
        run: |
          go vet .
